[package]
name = "docuflex-desktop"
version = "0.0.1"
description = "Docuflex offline PDF editor for macOS, Windows, and Linux"
authors = ["Maximilian Bayer"]
edition = "2021"

[lib]
name = "docuflex_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.6", features = [] }

[dependencies]
base64 = "0.22.1"
libc = "0.2.186"
rfd = "0.17.2"
tauri = { version = "2.11.5", features = ["devtools"] }
tauri-plugin-single-instance = "2.4.0"
url = "2.5.7"
